from enum import Enum

class Tag(Enum):
 # Fim de arquivo
 EOF = -1

 # Keywords
 KW_CLASS = 1
 KW_END = 2
 KW_DEF = 3
 KW_RETURN = 4
 KW_DEFSTATIC = 5
 KW_MAIN = 6
 KW_VOID = 7
 KW_STRING = 8
 KW_BOOL = 9
 KW_INTEGER = 10
 KW_DOUBLE = 11
 KW_IF = 12
 KW_ELSE = 13
 KW_WHILE = 14
 KW_WRITE = 15
 KW_TRUE = 16
 KW_FALSE = 17
 OP_OR = 18
 OP_AND = 19

 # Operators
 OP_SUM = 30
 OP_SUBTRACTION = 62
 OP_MULTIPLICATION = 31
 OP_DIVISION = 32
 OP_GREATER_EQUAL = 33
 OP_GREATER = 34
 OP_LESS_EQUAL = 35
 OP_LESS = 36
 OP_DIFFERENT = 37
 OP_EXCLAMATION = 38
 OP_ASSIGN = 39
 OP_NEGATION = 60
 OP_EQUAL = 61

 # Pontuation
 CHAR_TWO_POINTS = 40
 CHAR_COMMA = 41
 CHAR_POINT = 42
 CHAR_SEMICOLON = 43
 CHAR_OPEN_PARENTHESES = 50
 CHAR_CLOSE_PARENTHESES = 51
 CHAR_OPEN_SQUARE_BRACKETS = 52
 CHAR_CLOSE_SQUARE_BRACKETS = 53
 CHAR_OPEN_KEY = 54
 CHAR_CLOSE_KEY = 55

 # Identifier
 ID = 56

 # CONST
 INTEGER = 57
 DOUBLE = 58

 # String
 STRING = 59
